/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresStoreTableRouteImport } from './routes/stores.$store.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreTableRoute = StoresStoreTableRouteImport.update({
  id: '/stores/$store/$table',
  path: '/stores/$store/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stores/$store/$table': typeof StoresStoreTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stores/$store/$table': typeof StoresStoreTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stores/$store/$table': typeof StoresStoreTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stores/$store/$table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stores/$store/$table'
  id: '__root__' | '/' | '/stores/$store/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoresStoreTableRoute: typeof StoresStoreTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$store/$table': {
      id: '/stores/$store/$table'
      path: '/stores/$store/$table'
      fullPath: '/stores/$store/$table'
      preLoaderRoute: typeof StoresStoreTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoresStoreTableRoute: StoresStoreTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
