/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as LabyrinthRouteImport } from './routes/labyrinth'
import { Route as OracleRouteImport } from './routes/oracle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const LabyrinthRoute = LabyrinthRouteImport.update({
  id: '/labyrinth',
  path: '/labyrinth',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/labyrinth': typeof LabyrinthRoute
  '/oracle': typeof OracleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/labyrinth': typeof LabyrinthRoute
  '/oracle': typeof OracleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/labyrinth': typeof LabyrinthRoute
  '/oracle': typeof OracleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forge' | '/labyrinth' | '/oracle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forge' | '/labyrinth' | '/oracle'
  id: '__root__' | '/' | '/forge' | '/labyrinth' | '/oracle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgeRoute: typeof ForgeRoute
  LabyrinthRoute: typeof LabyrinthRoute
  OracleRoute: typeof OracleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labyrinth': {
      id: '/labyrinth'
      path: '/labyrinth'
      fullPath: '/labyrinth'
      preLoaderRoute: typeof LabyrinthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgeRoute: ForgeRoute,
  LabyrinthRoute: LabyrinthRoute,
  OracleRoute: OracleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
